Added docs directory to root
nzyuzin/teeworlds-ratings pull request #6
Opened 2017-04-20 23:37 UTC by CaptainAMN

Design doc and some other documentation

2017-04-20 23:41 UTC, nzyuzin commented on docs/rules-problems-solutions.txt
> +    Contact GitHub API Training Shop Blog About
This line clearly looks off.

2017-04-20 23:48 UTC, nzyuzin requested changes

2017-04-20 23:48 UTC, nzyuzin commented on docs/rules-problems-solutions.txt
> +Following added solutions to improve the matchmaking system. Shit ideas are enclosed by [.....]
Please avoid obscenities and bad words.

2017-04-20 23:48 UTC, nzyuzin commented on docs/rules-problems-solutions.txt
> +---> Righfully according to Shiki, this is not possible with the current implementation.
Style of that comment doesn't belong to documentation, please present the key idea for now, without additional info.

2017-04-20 23:48 UTC, nzyuzin commented on docs/rules-problems-solutions.txt
> +[Now, for capgames, in some special circumstances, people can fuck around on purpose and make this a pain in the ass, if they decide just to
Bad wording.

2017-04-20 23:48 UTC, nzyuzin commented on docs/rules-problems-solutions.txt
> +and then take appropriate measures against the user. For clanwars, i see this as a minor problem at best. Leaving games should be simply punished,
Personal opinions do not belong to documentation.

2017-04-20 23:48 UTC, nzyuzin commented on docs/rules-problems-solutions.txt
> +For example: If Sonix replaces Player A, the topscorer of team blue, Sonix will pick the game up with the same ingame points as Player D,
Please avoid referring by names and use neutral 'Player'.

2017-04-20 23:48 UTC, nzyuzin commented on docs/Designdocument.txt
> +=This is an unfinished draft=
Just leave it unfinished, no need to state it.

2017-04-20 23:48 UTC, nzyuzin commented on docs/Designdocument.txt
> +Alas,
Alas?

2017-04-20 23:48 UTC, nzyuzin commented on docs/Designdocument.txt
> +Design document is as follows:
Redundant line.

2017-04-20 23:48 UTC, nzyuzin commented on docs/Designdocument.txt
> +**************Our goal:
Here and in other places too many spaces between the lines.

2017-04-20 23:48 UTC, nzyuzin commented on docs/rules-problems-solutions.txt
> +---> We can never get this to work because of the required space to save all of the server side demos. NEEDS BETTER SOLUTION:
Looks like redundant comment.
Can you style the solutions like pros-cons instead?

2017-04-21 00:34 UTC, CaptainAMN commented
Hope this worked, thx for correcting.

2017-04-21 09:34 UTC, nzyuzin commented
Thanks!

2017-04-21 09:35 UTC, merged